use_frameworks!

platform :ios, '10.0'

target 'YJRetainCycleDetector_Example' do
  pod 'YJRetainCycleDetector', :path => '../'

  target 'YJRetainCycleDetector_Tests' do
    inherit! :search_paths
  end
end
